FROM ubuntu:16.04

MAINTANER Your Name "albu.silvana@gmail.com"

RUN apt-get update -y && \
    apt-get install -y python-pip python-dev

RUN apt-get install python3-tk

# We copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

COPY . /app

ENTRYPOINT [ "python" ]

CMD [ "/src/app.py" ]